### ISSUE TITLE
Suggestion: More stuff in API

### ISSUE THREAD

**Issue by Whizyyy** [Swisscypher/smartqueue-api#1]
Hey, is it possible to add more stuff in the API like these:

#isPlayerInQueue(Player player, String queue)
#getPlayerPositionInQueue(Player player, String queue)
#getPlayersInQueue(String queue)

**Comment by Zayceur** [comment]
Thanks for the suggestion.

The new functions are available in c1496f3757e8973c5dff8e093891c75ea0576fdf
