### ISSUE TITLE
Suggestion: More stuff in the API *again*

### ISSUE THREAD

**Issue by Whizyyy** [Swisscypher/smartqueue-api#2]
New function needed please:

#setToggleQueue(String queue, boolean toggle)

**Comment by Zayceur** [comment]
Thanks for the suggestion.

Two new functions are available in d4bc42b51ba9d3aeb44d8283d465ff6d5f6d0d3e :
- #setQueueStatus(String queue, boolean status)
- #getQueueStatus(String queue)
